### PR TITLE
Fix issues #4 ,#5, #6, #8

### PR DESCRIPTION
**Pull request by eemhu**
This pull request should fix issues #4 #5 #6 and #8 

* #4: hostname and appname are now configurable via "syslogHostname" and "syslogAppname" log opts.
* #5: instead of making our own SyslogMessage struct, a library is used that can handle structured data.
* #6: log opt "tag" can be used to change the id
* #8: each logPair has its own relp connection, instead of the whole driver.

Fixes for #9 will be on separate PR as it completes.

### CODE REVIEW

**Comment by kortemik** [comment]
syslogMsg.SetProcID(customLogTag)
Please verify that this does not exceed:
PROCID          = NILVALUE / 1*128PRINTUSASCII
where
      PRINTUSASCII    = %d33-126
meaning characters on ascii table between decimal number 33 and 126 (! .. ~)

**Comment by eemhu** [comment]
if procId contains invalid ascii char, should it panic, remove them, replace them or ignore the message?
currently it will log to plugin's stderr

**Comment by kortemik** [comment]
would it be more proper to place that into the structured data so it can contain any utf8 characters?

i'd prefer [dkr_01@48577 key=val] schema where all the parameters have their own key and assigned value instead of string concat method.

**Comment by eemhu** [comment]
> would it be more proper to place that into the structured data so it can contain any utf8 characters?
> 
> i'd prefer [dkr_01@48577 key=val] schema where all the parameters have their own key and assigned value instead of string concat method.

it would be possible to have this kind of schema:
```
2 syslog 462 '<4>1 2023-05-03T10:18:05Z fedora teragrep 9ac86f08f24d79f134160cd8a3f7a266cbfc9dba8d4f42462ab68ee58b8a69e5 - [dkr_01@48577 DaemonName="docker" FullID="9ac86f08f24d79f134160cd8a3f7a266cbfc9dba8d4f42462ab68ee58b8a69e5" ID="9ac86f08f24d" ImageFullID="sha256:580b7c6b7ad6fe2fa11ec304b09c3e4eec26733d6277d7d0bd7d7fddf83dd88c" ImageID="sha256:580b7" ImageName="testserver_test" Name="/testserver_test_1"] 2023/05/03 10:18:05 [TestServer] Start server on localhost 9003'

```
which the user can toggle with --log-opt tags=true|false, or maybe different levels? 0=off, 1=minimal (only first 12 chars  of IDs instead of full IDs) and 2=full which would have the full ID only

**Review by kortemik — APPROVED** [review]

**Pull request merged**
